services:
  postgres:
    image: postgres:15
    container_name: taskmanagement-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagement
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: .
  #   container_name: taskmanagement-api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: taskmanagement
  #     DB_PORT: 5432
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   command: ["npm", "run", "dev"] # Or "start" depending on your setup

volumes:
  postgres_data:
